add feature:OTP-Input,useRef

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -12,6 +12,11 @@ npm run format || {
   exit 1
 }
 
+npm run check-ts|| {
+  echo "❌ typescript correctnes failed. Please fix the errors before committing."
+  exit 1
+}
+
 echo "✅ All checks passed! Proceeding with commit..."
 
 
